"""Dump every native Live device's parameters (name, range, items, default display) from the running Live.

Adds each device to a "[test:devices]" scratch track (one audio, one MIDI), reads its parameters with get_device,
deletes the device, and finally deletes both scratch tracks one call each. Writes the JSON reference that
docs/production/reference/ is built from; regenerate it after a Live update:

    uv run python scripts/dump_device_parameters.py docs/production/reference/live-<version>-device-parameters.json
    uv run python scripts/dump_device_parameters.py --markdown docs/production/reference/live-<version>-device-parameters.json

Needs Live running with the AbletonMCP Remote Script; touches only its own scratch tracks.
"""
import json, sys, time
from MCP_Server.tools.devices import add_device, delete_device, get_device, get_devices
from MCP_Server.tools.tracks import create_track, delete_track, get_mixer

AUDIO = ["Amp", "Auto Filter", "Auto Pan-Tremolo", "Auto Shift", "Beat Repeat", "Cabinet", "Channel EQ", "Chorus-Ensemble",
         "Compressor", "Corpus", "Delay", "Drum Buss", "Dynamic Tube", "Echo", "EQ Eight", "EQ Three", "Erosion",
         "Filter Delay", "Gate", "Glue Compressor", "Grain Delay", "Hybrid Reverb", "Limiter", "Looper", "Multiband Dynamics",
         "Overdrive", "Pedal", "Phaser-Flanger", "Redux", "Resonators", "Reverb", "Roar", "Saturator", "Shifter",
         "Spectral Resonator", "Spectral Time", "Utility", "Vinyl Distortion", "Vocoder", "Align Delay", "Re-Enveloper",
         "Spectral Blur", "Tuner", "Spectrum"]
INSTRUMENTS = ["Analog", "Collision", "Drift", "Electric", "Impulse", "Meld", "Operator", "Sampler", "Simpler", "Tension",
               "Wavetable", "Granulator III", "Poli", "Bass", "Emit", "Vector FM", "Vector Grain", "Tree Tone"]
MIDI_FX = ["Arpeggiator", "Chord", "Note Length", "Pitch", "Random", "Scale", "Velocity", "CC Control", "MIDI Monitor",
           "Expression Control"]


def dump(track, names, out):
    for name in names:
        try:
            add_device(track, name)
        except Exception as error:
            out[name] = {"error": str(error)[:200]}
            print("skip", name, str(error)[:80], flush=True)
            continue
        devices = get_devices(track)["devices"]
        index = len(devices) - 1
        info = get_device(track, index)
        params = []
        for p in info.get("parameters", []):
            row = {"name": p["name"], "display": p.get("display"), "min": p.get("min"), "max": p.get("max")}
            if p.get("items"):
                row["items"] = p["items"]
            params.append(row)
        out[name] = {"class": devices[index].get("class"), "class_name": info.get("class_name"),
                     "loaded_as": devices[index].get("name"), "parameters": params}
        print("%-20s %3d parameters" % (name, len(params)), flush=True)
        delete_device(track, index)
        time.sleep(0.2)


def markdown(json_path):
    """A compact, readable companion: every parameter name per device, enumerations with their items."""
    data = json.load(open(json_path))
    lines = ["# Live {0} device parameters".format(data["live"]), "",
             "Generated by `scripts/dump_device_parameters.py` from the running Live (parameter names exactly as",
             "`get_device` reports them; defaults are a freshly added device). Use these names with",
             "`set_device_parameters`; pass display strings (\"-6 dB\", \"800 Hz\", \"30 %\") or item names.",
             "Ranges in brackets are Live's raw ranges, which for many parameters are 0..1. The JSON next to this file",
             "has min, max and items for every parameter.", ""]
    for group, title in (("audio_effects", "Audio effects"), ("instruments", "Instruments"), ("midi_effects", "MIDI effects")):
        lines += ["## " + title, ""]
        for name in sorted(data[group]):
            info = data[group][name]
            if "error" in info:
                continue
            parts = []
            for p in info["parameters"]:
                if p["name"] == "Device On":
                    continue
                if p.get("items"):
                    parts.append("{0} {{{1}}}".format(p["name"], ", ".join(str(i) for i in p["items"])))
                else:
                    parts.append("{0} ({1})".format(p["name"], p.get("display")))
            lines += ["### " + name, "", "; ".join(parts), ""]
    out = json_path.rsplit(".", 1)[0] + ".md"
    with open(out, "w") as handle:
        handle.write("\n".join(lines))
    print("wrote", out)


def main():
    if sys.argv[1] == "--markdown":
        markdown(sys.argv[2])
        return
    out_path = sys.argv[1]
    result = {"live": "12.4.6 Suite", "note": "Parameter names, ranges and items as Live reports them through the "
              "Remote Script (get_device). 'display' is the default value of a freshly added device.",
              "audio_effects": {}, "instruments": {}, "midi_effects": {}}
    audio, midi = "[test:devices] audio", "[test:devices] midi"
    create_track("audio", name=audio)
    create_track("midi", name=midi)
    try:
        dump(audio, AUDIO, result["audio_effects"])
        dump(midi, MIDI_FX, result["midi_effects"])
        dump(midi, INSTRUMENTS, result["instruments"])
    finally:
        with open(out_path, "w") as handle:
            json.dump(result, handle, indent=1)
        names = [t["name"] for t in get_mixer()["tracks"]]
        for track in (audio, midi):
            if track in names:
                delete_track(track)
                time.sleep(0.4)
    print("wrote", out_path)


if __name__ == "__main__":
    main()
